name: Deploy to AWS Lightsail 
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions: 
  id-token: write 
  contents: read 

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Substituir variáveis no settings.xml
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_TOKEN: ${{ secrets.MAVEN_PASSWORD }}
      run: envsubst < settings.xml.j2 > settings.xml

    - name: mostrar settings.xml
      run: cat settings.xml && pwd

    - name: Configure AWS credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}    
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID && aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY && aws configure set default.region $AWS_REGION


    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      run: |
        docker build -t patrick:latest .
        docker tag patrick:latest 794196173640.dkr.ecr.us-east-2.amazonaws.com/patrick:latest
        docker push 794196173640.dkr.ecr.us-east-2.amazonaws.com/patrick:latest


    - name: Deploy deployment.json
      run: |
        cat > deployment.json << EOF
        {
        "container-service-group10": {
            "image": "794196173640.dkr.ecr.us-east-2.amazonaws.com/patrick:latest",
            "command": [],
            "environment": {
              "DB_URL": "${{ secrets.DB_URL }}",
              "DB_USERNAME": "${{ secrets.DB_USERNAME }}",
              "DB_PASSWORD": "${{ secrets.DB_PASSWORD }}",
              "JWT_SECRET": "${{ secrets.JWT_SECRET }}",
              "JWT_EXPIRATION": "${{ secrets.JWT_EXPIRATION }}",
              "JWT_ISSUER": "${{ secrets.JWT_ISSUER }}",
              "PLUGGY_CLIENT_ID": "${{ secrets.PLUGGY_CLIENT_ID }}",
              "PLUGGY_CLIENT_SECRET": "${{ secrets.PLUGGY_CLIENT_SECRET }}",
              "GOOGLE_API_KEY": "${{ secrets.GOOGLE_API_KEY }}",
              "CHAT_GPT_API_KEY": "${{ secrets.CHAT_GPT_API_KEY }}",
              "SPRING_MAIL_HOST": "${{ secrets.SPRING_MAIL_HOST }}",
              "SPRING_MAIL_PORT": "${{ secrets.SPRING_MAIL_PORT }}",
              "SPRING_MAIL_USERNAME": "${{ secrets.SPRING_MAIL_USERNAME }}",
              "SPRING_MAIL_PASSWORD": "${{ secrets.SPRING_MAIL_PASSWORD }}",
              "ACTIVE_PROFILE": "${{ secrets.ACTIVE_PROFILE }}"
              
            },
            "ports": {
              "80": "HTTP",
              "8080": "HTTP"
            }
        }
        }
        EOF
        cat deployment.json

    - name: Deploy public-endpoint.json
      run: |
        cat > public-endpoint.json << EOF
        {
          "containerName": "container-service-group10",
          "containerPort": 8080,
          "healthCheck": {
              "path": "/actuator/health",
              "timeoutSeconds": 10,
              "intervalSeconds": 50,
              "healthyThreshold": 3,
              "unhealthyThreshold": 3,
              "successCodes": "200-499"
          }
        }
        EOF
        cat public-endpoint.json
      


    - name: Deploy AWS Lightsail container
      run: >
        aws lightsail create-container-service-deployment 
        --service-name container-service-group10 
        --region us-east-2 
        --containers file://deployment.json 
        --public-endpoint file://public-endpoint.json
